<?php

/**
 * @file
 * Defines the veritrans payment gateway.
 */

/**
 * Implements hook_libraries_info().
 */
function uc_veritrans_libraries_info() {
  $libraries['veritrans'] = array(
    'name' => 'PHP client library for Veritrans',
    'vendor url' => 'https://github.com/veritrans/veritrans-php',
    'download url' => 'https://github.com/veritrans/veritrans-php/archive/master.zip',
    'path' => 'Veritrans',
    'version arguments' => array(
      'file' => 'README.md',
      'pattern' => '/Veritrans (\d+)/',
      'lines' => 6,
    ),
    'files' => array(
      'php' => array(
        'Config.php',
        'Transaction.php',
        'ApiRequestor.php',
        'Notification.php',
        'VtDirect.php',
        'VtWeb.php',
        'Sanitizer.php',
      ),
    ),
  );

  return $libraries;
}

/**
 * Implements hook_menu().
 */
function uc_veritrans_menu() {
  $items = array();

  $items['vt_web/%uc_order'] = array(
    'title' => 'Veritrans payment complete',
    'page callback' => 'uc_veritrans_vtweb_payment_complete',
    'page arguments' => array(1),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'uc_veritrans.inc',
  );

  $items['vt_web/notify'] = array(
    'title' => 'Vt Web Payment Notificataion',
    'page callback' => 'uc_veritrans_vt_web_payment_notification',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'uc_veritrans.inc',
  );

  $items['vt_web/success'] = array(
    'title' => 'Vt Web Payment Success',
    'page callback' => 'uc_veritrans_vt_web_payment_success',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'uc_veritrans.inc',
  );

  $items['vt_web/unfinish'] = array(
    'title' => 'Vt Web Payment Unfinsh',
    'page callback' => 'uc_veritrans_vt_web_payment_unfinish',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'uc_veritrans.inc',
  );

  $items['vt_web/error'] = array(
    'title' => 'Vt Web Payment Error',
    'page callback' => 'uc_veritrans_vt_web_payment_error',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'uc_veritrans.inc',
  );

  return $items;
}

/**
 * Implements hook_uc_payment_method().
 */
function uc_veritrans_uc_payment_method() {
  $methods['vt_web'] = array(
    'name' => t('Veritrans'),
    'title' => t('Veritrans'),
    'review' => t('Veritrans'),
    'desc' => t('Redirect users to submit payments through Veritrans.'),
    'callback' => 'uc_veritrans_payment_method_vt_web',
    'redirect' => 'uc_veritrans_vt_web_payment_form',
    'weight' => 1,
    'checkout' => FALSE,
    'no_gateway' => TRUE,
  );
  return $methods;
}

/**
 * Veritrans checkout page alter.
 */
function uc_veritrans_vt_web_payment_form($form, &$form_state, $order) {
  $form['#action'] = url('vt_web/' . $order->order_id);
  $form['#method'] = 'GET';

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Proceed to payment'),
  );
  return $form;
}

/**
 * Veritrans settings page.
 */
function uc_veritrans_payment_method_vt_web($op, &$arg1) {
  switch ($op) {
    case 'settings':
      $form['uc_veritrans_server_key'] = array(
        '#type' => 'textfield',
        '#title' => t('Server Key'),
        '#description' => t('Your Veritrans Server key.'),
        '#default_value' => variable_get('uc_veritrans_server_key', ''),
        '#size' => 50,
        '#required' => TRUE,
      );

      $form['uc_veritrans_payment_mode'] = array(
        '#type' => 'select',
        '#title' => t('Payment mode'),
        '#description' => t('The mode for capturing payment.'),
        '#options' => array(
          'LIVE' => t('Live transactions'),
          'TEST' => t('Test transactions'),
        ),
        '#default_value' => variable_get('uc_veritrans_payment_mode', ''),
      );
      $form['uc_veritrans_error_redirect_url'] = array(
        '#type' => 'textfield',
        '#title' => t('Error Url'),
        '#description' => t('The mode for error url.'),
        '#default_value' => variable_get('uc_veritrans_error_redirect_url', ''),
        '#element_validate' => array('uc_veritrans_link_validate'),
      );
      $form['uc_veritrans_unfinish_redirect_url'] = array(
        '#type' => 'textfield',
        '#title' => t('Unfinish Url'),
        '#description' => t('The mode for unfinish url.'),
        '#default_value' => variable_get('uc_veritrans_unfinish_redirect_url', ''),
        '#element_validate' => array('uc_veritrans_link_validate'),
      );
      $form['uc_veritrans_finish_redirect_url'] = array(
        '#type' => 'textfield',
        '#title' => t('Finish Url'),
        '#description' => t('The mode for finish url.'),
        '#default_value' => variable_get('uc_veritrans_finish_redirect_url', ''),
        '#element_validate' => array('uc_veritrans_link_validate'),
      );
      $form['uc_veritrans_debugging'] = array(
        '#type' => 'checkbox',
        '#title' => t('Debug'),
        '#description' => t('Check the response from veritrans.'),
        '#default_value' => variable_get('uc_veritrans_debugging', FALSE),
      );
      return $form;
  }
}

/**
 * Link Validation.
 */
function uc_veritrans_link_validate($element, &$form_state) {
  $element_name = $element['#name'];
  $values = $form_state['values'];
  $path = drupal_get_normal_path($values[$element_name]);
  if (!trim($path) || !drupal_valid_path($path, TRUE)) {
    form_set_error($element_name, t("The path '@path' is invalid.", array('@path' => $path)));
  }
}

/**
 * IPN for veritrans payment gateway.
 */
function uc_veritrans_vt_web_payment_notification() {
  libraries_load('veritrans');
  $notification = new Veritrans_Notification();
  if (empty($notification->order_id)) {
    $error_redirect_url = variable_get('uc_veritrans_error_redirect_url', 'vt_web/error');
    drupal_goto($error_redirect_url);
  }
  $order = uc_order_load($notification->order_id);
  if (variable_get('uc_veritrans_debugging', FALSE)) {
    watchdog('vt_web', 'Response from Veritrance  <pre>!response</pre>', array('!response' => print_r($notification, TRUE)), WATCHDOG_DEBUG);
  }

  if ($order == FALSE) {
    watchdog('vt_web', 'IPN attempted for non-existent order @order_id.', array('@order_id' => $notification->order_id), WATCHDOG_ERROR);
    return FALSE;
  }
  // Exit now if the $_POST was empty.
  if (empty($notification)) {
    watchdog('vt_web', 'Notification URL accessed with no POST data.', array(), WATCHDOG_WARNING);
    return FALSE;
  }

  Veritrans_Config::$serverKey = variable_get('uc_veritrans_server_key', '');
  $result = Veritrans_Transaction::status($notification->order_id);
  if ($result->transaction_id != $notification->transaction_id || $result->fraud_status != $notification->fraud_status) {
    watchdog('vt_web', 'Verification of transaction failed.', array(), WATCHDOG_WARNING);
    return FALSE;
  }
  $transaction = $notification->transaction_status;
  $fraud = $notification->fraud_status;
  if ($transaction == 'capture') {
    if ($fraud == 'challenge') {
      // TODO Set payment status in merchant's database to 'challenge'.
      uc_order_update_status($order->order_id, 'vt_web_pending');
      uc_order_comment_save($order->order_id, 0, t('Payment is pending at Veritrans'), 'admin');
    }
    elseif ($fraud == 'accept') {
      // TODO Set payment status in merchant's database to 'success'.
      // Update order state set to paid.
      $order->order_total = round($order->order_total, 2);
      $payment_amount = $order->order_total;
      $context = array(
        'revision' => 'formatted-original',
        'type' => 'amount',
      );
      $options = array(
        'sign' => TRUE,
      );

      // Confirm payment.
      $payment_message = t('Payment using Veritrans. ORDERNUMBER: @ordernumber.', array('@ordernumber' => $order->order_id));
      uc_payment_enter($order->order_id, 'vt_web', $order->order_total, $order->uid, NULL, $payment_message);
      uc_cart_complete_sale($order, FALSE);
      uc_order_update_status($order->order_id, 'payment_received');
      $webpay_amount = array(
        '@amount' => uc_price($payment_amount, $context, $options),
      );
      $payment_submitted = t('Payment of @amount submitted through Veritrans.', $webpay_amount);
      uc_order_comment_save($order->order_id, 0, $payment_submitted, 'order', 'payment_received');
      $payment_reported = t('Veritrans  reported a payment of @amount.', $webpay_amount);
      uc_order_comment_save($order->order_id, 0, $payment_reported);
    }
  }
  elseif ($transaction == 'cancel') {
    if ($fraud == 'challenge' || $fraud == 'accept') {
      // TODO Set payment status in merchant's database to 'failure'.
      $webpay_error = t('Payment declined by merchant.');
      uc_order_comment_save($order->order_id, 0, $webpay_error);
    }
  }
  elseif ($transaction == 'deny') {
    // TODO Set payment status in merchant's database to 'failure'.
    $webpay_error = t('Payment declined by merchant.');
    uc_order_comment_save($order->order_id, 0, $webpay_error);
  }
  else {
    watchdog('vt_web', 'Something went wrong, please contact site administrator.');
  }
}
